format = """
╭─[](#F6F1F1)\
$env_var\
[](bg:#19A7CE fg:#F6F1F1)\
$directory\
[](fg:#19A7CE bg:#146C94)\
$git_branch\
$git_status\
[](fg:#146C94 bg:#0B5374)\
$aws\
$c\
$dart\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$rust\
$scala\
$php\
$python\
$docker_context\
$kubernetes\
[](fg:#0B5374 bg:#000000)\
$cmd_duration\
$time\
$hostname\
[ ](fg:#000000)
╰─$character\
"""

#---

add_newline = false
command_timeout = 500
scan_timeout = 30
right_format = ''

#---

[character]
# ➜❯
success_symbol = '[❯](#3D85C6)'
error_symbol = '[❯](#CC0000)'

#---

[env_var.STARSHIP_DISTRO]
format = '[$env_value  ]($style)'
style = "bg:#F6F1F1 fg:#090C0C"
variable = "STARSHIP_DISTRO"
disabled = false

# [env_var.USER]
# format = '[$env_value ]($style)'
# style = "bg:#F6F1F1 fg:#090C0C"
# variable = "USER"
# disabled = false

[env_var.STARSHIP_DEVICE]
style = "bg:#F6F1F1 fg:#090C0C"
format = '[$env_value]($style)'
variable = "STARSHIP_DEVICE"
disabled = false

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#F6F1F1 bg:#19A7CE"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "red"
home_symbol = "~"

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Videos" = ""

[git_branch]
symbol = ""
style = "fg:#F6F1F1 bg:#146C94"
format = "[ $symbol $branch ]($style)"
truncation_symbol = "…/"

[git_status]
format = '[$all_status $ahead_behind]($style)'
style = "fg:#F6F1F1 bg:#146C94"
conflicted = "🏳"
up_to_date = ""
untracked = ""
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[++$count](fg:#FFD966 bg:#146C94)'
stashed = ""
modified = ""
renamed = "襁"
deleted = ""

[nodejs]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[rust]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[golang]
symbol = "ﳑ"
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[php]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#000000"
format = '[[  $time](fg:#A0A9CB bg:#000000)]($style)'

[hostname]
disabled = false
ssh_symbol = ""
ssh_only = true
style = "bg:#000000"
format = '[[ $ssh_symbol $hostname ($version)](fg:#A0A9CB bg:#000000)]($style)'

[cmd_duration]
disabled = false
style = "bg:#000000"
format = '[[  $duration](fg:#FFFFFF bg:#000000)]($style)'

[docker_context]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol $context](fg:#F6F1F1 bg:#0B5374)]($style)'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
disabled = false
only_with_files = true

[kubernetes]
symbol = "ﴱ"
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol $context\($namespace\)](fg:#F6F1F1 bg:#0B5374)]($sytle) '
disabled = false

[python]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'
python_binary = ['python', 'python3', 'python2']
detect_extensions = ['py']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
disabled = false
pyenv_version_name = false
pyenv_prefix = "pyenv"

[aws]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[c]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[java]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[gradle]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[lua]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[ruby]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[dart]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[haskell]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

#---

[buf]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[conda]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[elixir]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[elm]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[hg_branch]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[julia]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[memory_usage]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[meson]
symbol = "喝"
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[nim]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[nix_shell]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

# [os.symbols]
# Alpaquita = " "
# Alpine = " "
# Amazon = " "
# Android = " "
# Arch = " "
# Artix = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "﯑ "
# Gentoo = " "
# HardenedBSD = "ﲊ "
# Illumos = " "
# Linux = " "
# Mabox = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = " "
# openSUSE = " "
# OracleLinux = " "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# Redox = " "
# Solus = "ﴱ "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Windows = " "

[package]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[rlang]
symbol = "ﳒ"
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'


[scala]
symbol = ""
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'

[spack]
symbol = "🅢"
style = "fg:#F6F1F1 bg:#0B5374"
format = '[[ $symbol ($version)](fg:#F6F1F1 bg:#0B5374)]($style)'